### ISSUE TITLE
Support for Pandoc fenced divs, bracketed spans, and header/table attributes.

### ISSUE THREAD

**Issue by somelinguist** [ApexMarkdown/apex#3]
One thing I use extensively with Pandoc are fenced divs and bracketed spans. The syntax for header attributes can be used with each of these. It looks similar but different to the syntax for IALs in Kramdown.

In Pandoc, these are helpful features both for styling, and also for writing custom filters/extensions to easily find what should be transformed.

https://pandoc.org/demo/example33/8.18-divs-and-spans.html

```markdown
::: fencedDiv
Some text

::: nestedDiv
A nested div

:::

:::

The syntax above results in divs with the classes `.fencedDiv` and `.nestedDiv`,m respectively.

The full range of attributes can be expressed inside brackets:

::: { #ident .class key="value" anotherkey=4 yetanotherkey }
A div with attributes (including id, class(es) and other attribute/value pairs
:::

Bracketed [spans]{#ident .class key="value" key } with attributes.

```

https://pandoc.org/demo/example33/8.3-headings.html#extension-header_attributes

```markdown
# Heading { #ident .unnumbered }
```

More recently, the attributes can also be used with tables after the caption.

https://pandoc.org/demo/example33/8.9-tables.html#extension-table_attributes

```markdown
| One | Two   |
|-----+-------|
| my  | table |
| is  | nice  |

: Here's the caption. {#ident .class key="value"}

```

**Comment by ttscoff** [comment]
Ok, thus far I have support for Pandoc's IAL syntax, though right now it only works with classes and ids, not with attributes. Still working on that. And I have the ability to add IALs to table captions and apply them to the table, as well as handling `: caption` (without "Table:"). Working on the divs now.

I had considered bracketed spans when I was working on the IALs but skipped it under the assumption that no one had implemnted it already, but knowing that Pandoc does (at least via extension), I'll take another look at it.

- [x] Support for "Table:", "table:" and ":" for table captions
- [x] Support for IALs not beginning with a colon
- [x] Support for IALs in table captions applied to table
- [ ] Div extension
- [ ] Bracketed spans

**Comment by somelinguist** [comment]
Thanks again! This will be really useful, especially if it makes it into Marked 3.

It looks like the divs and spans work as expected.

Table captions are only getting picked up immediately following the table. If there is a line in between the table and the caption (as in the [blog example](https://brettterpstra.com/2026/01/01/additional-pandoc-features-for-apex/#table-captions-get-more-flexible), as well as [Pandoc examples](https://pandoc.org/demo/example33/8.9-tables.html)), it's not working, and it also misses the last row of the table:

```markdown
| Col1 | Col2 |
|------|------|
| A    | B    |

: My Table {#table-id .highlight}
```
 results in:

```html
<table>
<thead>
<tr>
<th>Col1</th>
<th>Col2</th>
</tr>
</thead>
</table>
<p>| A    | B    |</p>
<p>[My Table] {#table-id .highlight}</p>
```

This seems to be the case with the `Table: My Table` variant as well, with or without the IAL.

Without the extra line space, the colon only version picks up the caption and parses out the IAL, but it doesn't apply the IAL:

```markdown
| Col1 | Col2 |
|------|------|
| A    | B    |
: My Table {#table-id .highlight}
```

results in:

```html
<figure class="table-figure">
<table>
<tbody>
<tr>
<td>Col1</td>
<td>Col2</td>
</tr>
<tr>
<td>A</td>
<td>B</td>
</tr>
</tbody>
</table><figcaption>My Table</figcaption>
</figure>
```

And the `Table:` version without a line break picks up the caption, but doesn't parse out the IAL:

```markdown
| Col1 | Col2 |
|------|------|
| A    | B    |
Table: My Table {#table-id .highlight}
```



results in:

```html
<figure class="table-figure">
<table>
<tbody>
<tr>
<td>Col1</td>
<td>Col2</td>
</tr>
<tr>
<td>A</td>
<td>B</td>
</tr>
</tbody>
</table><figcaption>My Table {#table-id .highlight}</figcaption>
</figure>
```

I compiled/installed from source with v0.1.43.

**Comment by ttscoff** [comment]
Ok, 0.1.46 fixes the table caption issues. All of your examples are working for me. This whole bug was a case of "it works on MY machine," though, so please test before I close out the issue.

**Comment by ttscoff** [comment]
For the sake of completeness, I'll see if I can separate the definition 
list from the caption syntax. I ran into a similar issue where 
definition lists were being too aggressively detected and converted even 
inside of code blocks. I need to revisit that code/code order.

Definition lists should always be in the format:

```
Term
: Definition
```

If there's no term, it shouldn't be a DL.

I'll look into it and see if I can support the `: Caption` before a 
table better.

Thanks,
Brett

**Comment by somelinguist** [comment]
Thanks for figuring things out! I built from source and did the following tests:

1. If `:caption` precedes the table, and there is a paragraph followed by one ore more blank lines before `:caption`, then there's a segmentation fault:

```markdown
# Tables
Test this table.

: My Table {#table-id .highlight}
| Col1 | Col2 |
|------|------|
| A    | B    |
```

```
[1]    48720 segmentation fault    apex '/path/to/file.md'
```

2. Without a preceding paragraph, the `:caption` version works preceding the table now (IALs are fine too):

```markdown
# Tables

: My Table {#table-id .highlight}
| Col1 | Col2 |
|------|------|
| A    | B    |
```

3. The `Table: caption` version works fine with or without the preceding paragraphs (IALs are fine too).

```markdown
# Tables

Table: My Table {#table-id .highlight}
| Col1 | Col2 |
|------|------|
| A    | B    |
```

```markdown
# Tables
Test this table.

Table: My Table {#table-id .highlight}
| Col1 | Col2 |
|------|------|
| A    | B    |
```

4. Captions following the table seem to work fine with both versions (IALs are fine too):

```markdown
# Tables
Test this table.

| Col1 | Col2 |
|------|------|
| A    | B    |
: My Table {#table-id .highlight}

Test this table.

| Col1 | Col2 |
|------|------|
| A    | B    |
Table: My Table {#table-id2 .highlight}
```


5. Definition lists seem to work fine.

**Comment by somelinguist** [comment]
I forgot to test a line break following the table and then the caption:

```markdown
# Tables
 Test this table.
 
| Col1 | Col2 |
|------|------|
| A    | B    |

: My Table {#table-id .highlight}

Test this table.

| Col1 | Col2 |
|------|------|
| A    | B    |

Table : My Table {#table-id2 .highlight}
```

These versions both don't parse the last row of the table, and they miss the caption and the IALs:

```html
<h1 id="tables">Tables</h1>
<p>Test this table.</p>
<table>
<thead>
<tr>
<th>Col1</th>
<th>Col2</th>
</tr>
</thead>
</table>
<p>| A    | B    |</p>
<p>[My Table] {#table-id .highlight}</p>
<p>Test this table.</p>
<table>
<thead>
<tr>
<th>Col1</th>
<th>Col2</th>
</tr>
</thead>
</table>
<p>| A    | B    |Table : My Table {#table-id2 .highlight}</p>
```

**Comment by somelinguist** [comment]
1. The segmentation fault is fixed.

2. My first test of the second issue still led to bad results (thought they weren't as bad). But after doing some further testing, similar results sometimes showed up elsewhere. Specifically, the last row of the first table often was not parsed:

```html
<figure class="table-figure">
<table data-caption="My Table" id="table-id" class="highlight">
<tbody>
<tr>
<td>Col1</td>
<td>Col2</td>
</tr>
</table><figcaption>My Table</figcaption>
</figure>

<p>| A    | B    |
Test this table.</p>
...
```

Trying to make it simpler, I took off the IALs, and then I got the following error:

```bash
apex(58530,0x20caf2240) malloc: *** error for object 0x600000af4680: pointer being freed was not allocated
apex(58530,0x20caf2240) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    58530 abort      apex '/path/to/test-table.md'
```

That seemed strange and new, and that's when I noticed that I didn't have a line break after the final caption at the end of the file:

```markdown
# Tables

Test this table.

| Col1 | Col2 |
|------|------|
| A    | B    |

: My Table {#table-id .highlight}

Test this table.

| Col1 | Col2 |
|------|------|
| A    | B    |

Table: My Table {#table-id2 .highlight}
```

Adding a final line break seems to fixe the allocation error, and removing it brings it back in the allocation error when the file above. Interestingly, the allocation error doesn't happen if I move the first caption to before the first table, it just doesn't parse the first table correctly.

However, adding the final blank line does consistently solve the last row of the first table and everything else getting parsed correctly, even with the IALs., and removing it causes issues.

Do you have any thoughts?

**Comment by ttscoff** [comment]
Tables are turning out to be a huge pain. The error you got doesn’t make sense initially, but I’ll try to replicate and trace. If fixing both issues is as simple as forcing a new line…

- Brett

**Comment by somelinguist** [comment]
I just looked through the build logs and saw two warnings:

```
CMake Warning at CMakeLists.txt:59 (message):
  libyaml not found.  YAML arrays and nested structures will not be
  supported.
```

```
CMake Deprecation Warning at vendor/cmark-gfm/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.
```

**Comment by somelinguist** [comment]
Here's the file I made copying and pasting from your comment.

[test-table2.md](https://github.com/user-attachments/files/24509043/test-table2.md)

**Comment by ttscoff** [comment]
Ah, I think that explains it. Needed to ensure a \n when there was only a \r on the last line (cmark handles this natively, but not all of my extensions were). Should be fixed now. Tests are passing anyway, and the most recent examples work for me.

**Comment by somelinguist** [comment]
That makes sense.

I'm still getting the same behavior though.

Would I need to do anything more than this for the extensions?

```bash
git pull
make
make install
```

**Comment by ttscoff** [comment]
No, that should do it. I’ll see if I can find any way to still replicate.

- Brett

**Comment by ttscoff** [comment]
Ok, there are a lot of things that don't make sense about this. Sometimes when I compiled it broke the way you're seeing, sometimes not. I started working on the newline normalization, and every time I got that working, I started getting failing tests. I think I finally have both the newline issue and all tests working, and I've added a regression test for the newline fix to make sure it doesn't come up again. Please tell me this one works for you!

**Comment by ttscoff** [comment]
Oh wtf. If I had any hair...

Digging back in.

**Comment by ttscoff** [comment]
Thanks so much for the detailed testing, I never would have caught the issues with CR/CRLF. I missed fixing the CRLF case with the longer table captions. Should be fixed now. Let me know if we're there yet.
